// Generated by scripts/ucode_optimize.py; do not edit.
localparam logic [2:0] RECIPE_EARLY_SEQ    = 3'd0;
localparam logic [2:0] RECIPE_EARLY_NONE   = 3'd1;
localparam logic [2:0] RECIPE_EARLY_EA     = 3'd2;
localparam logic [2:0] RECIPE_EARLY_LOAD   = 3'd3;
localparam logic [2:0] RECIPE_EARLY_STORE  = 3'd4;
localparam logic [2:0] RECIPE_EARLY_RMW    = 3'd5;
localparam logic [2:0] RECIPE_EARLY_BRANCH = 3'd6;
localparam logic [2:0] RECIPE_EARLY_STACK  = 3'd7;

localparam logic [2:0] RECIPE_ACTION_NONE = 3'd0;
localparam logic [2:0] RECIPE_ACTION_X87_OVERLAY = 3'd1;
localparam logic [2:0] RECIPE_ACTION_INVLPG = 3'd2;
localparam logic [2:0] RECIPE_ACTION_RMW_FAST = 3'd3;
localparam logic [2:0] RECIPE_ACTION_CACHE_FLUSH = 3'd4;

// Resolve opcode-qualified overlays during D1 structural decode.
function automatic logic [11:0] recipe_effective_entry(
    input logic [11:0] entry,
    input logic [7:0] opcode,
    input logic [7:0] modrm
);
    recipe_effective_entry = entry;
    unique case (entry)
        12'h4D7: begin
            if ((opcode == 8'hD8) || ((opcode == 8'hD9) && (modrm[5:3] == 3'd0)))
                recipe_effective_entry = 12'h9C5;
        end
        12'h4C1: begin
            if (modrm[7:6] == 2'b11)
                recipe_effective_entry = 12'h9D1;
        end
        12'h53C: begin
            if ((modrm[7:6] != 2'b11) && ((opcode == 8'hD9) || (opcode == 8'hDB)) && ((modrm[5:3] == 3'd2) || (modrm[5:3] == 3'd3)))
                recipe_effective_entry = 12'h9D3;
        end
        12'h04A: begin
            if (modrm[7:6] != 2'b11)
                recipe_effective_entry = 12'h9CB;
        end
        12'h04E: begin
            if ((modrm[7:6] != 2'b11) && ((((opcode == 8'hF6) || (opcode == 8'hF7)) && ((modrm[5:3] == 3'd2) || (modrm[5:3] == 3'd3))) || (((opcode == 8'hFE) || (opcode == 8'hFF)) && ((modrm[5:3] == 3'd0) || (modrm[5:3] == 3'd1)))))
                recipe_effective_entry = 12'h9CE;
        end
        12'h0B6: begin
            if (opcode == 8'h90)
                recipe_effective_entry = 12'h9C9;
        end
        default: ;
    endcase
endfunction

function automatic logic [11:0] recipe_fallback_entry(input logic [11:0] entry);
    unique case (entry)
        12'h9C5: recipe_fallback_entry = 12'h4D7;
        12'h9D1: recipe_fallback_entry = 12'h4C1;
        12'h9D3: recipe_fallback_entry = 12'h53C;
        12'h9CB: recipe_fallback_entry = 12'h04A;
        12'h9CE: recipe_fallback_entry = 12'h04E;
        default: recipe_fallback_entry = entry;
    endcase
endfunction

function automatic logic [2:0] recipe_action(input logic [11:0] entry);
    unique case (entry)
        12'h9C5: recipe_action = RECIPE_ACTION_X87_OVERLAY;
        12'h9D1: recipe_action = RECIPE_ACTION_X87_OVERLAY;
        12'h9D3: recipe_action = RECIPE_ACTION_X87_OVERLAY;
        12'h9CB: recipe_action = RECIPE_ACTION_RMW_FAST;
        12'h9CE: recipe_action = RECIPE_ACTION_RMW_FAST;
        12'h9C7: recipe_action = RECIPE_ACTION_INVLPG;
        12'h9F3: recipe_action = RECIPE_ACTION_CACHE_FLUSH;
        default: recipe_action = RECIPE_ACTION_NONE;
    endcase
endfunction

function automatic logic [2:0] recipe_early_kind(input logic [11:0] entry);
    unique case (entry)
        12'h003, 12'h005, 12'h01D, 12'h01F, 12'h021, 12'h023, 12'h025, 12'h0F9, 12'h0FC, 12'h0FF, 12'h102, 12'h105, 12'h1E8, 12'h1F0, 12'h9C9, 12'h9D1: recipe_early_kind = RECIPE_EARLY_NONE;
        12'h0B9: recipe_early_kind = RECIPE_EARLY_EA;
        12'h019, 12'h027, 12'h02C, 12'h031, 12'h035, 12'h1EB, 12'h1F3, 12'h9C5: recipe_early_kind = RECIPE_EARLY_LOAD;
        12'h013, 12'h015: recipe_early_kind = RECIPE_EARLY_STORE;
        12'h039, 12'h04A, 12'h9CB, 12'h9CE: recipe_early_kind = RECIPE_EARLY_RMW;
        12'h065, 12'h06A: recipe_early_kind = RECIPE_EARLY_BRANCH;
        12'h072, 12'h075, 12'h086, 12'h09B, 12'h09D, 12'h09F: recipe_early_kind = RECIPE_EARLY_STACK;
        default: recipe_early_kind = RECIPE_EARLY_SEQ;
    endcase
endfunction

// Architectural GPR inputs needed by a hardwired recipe. The full recipe
// classifier separately qualifies legality; this compact D1 sidecar only
// removes deferred-write hazard decoding from the issue critical path.
function automatic logic [7:0] recipe_gpr_read_mask(input dec_entry_t e);
    logic [7:0] mask;
    logic op_byte;
    logic [2:0] dst_idx, src_idx;
    mask = e.stack_op ? 8'h10 : 8'h00;
    if (e.opcode[7:4] == 4'h4 || e.opcode[7:4] == 4'h5)
        op_byte = 1'b0;
    else if (e.opcode[7:4] == 4'hB && !e.has_0f)
        op_byte = !e.opcode[3];
    else
        op_byte = !e.opcode[0];
    dst_idx = op_byte ? {1'b0, e.dst_reg_sel[1:0]} : e.dst_reg_sel;
    src_idx = op_byte ? {1'b0, e.src_reg_sel[1:0]} : e.src_reg_sel;
    unique case (e.entry_point)
        12'h003, 12'h013: mask[src_idx] = 1'b1;
        12'h01D, 12'h01F, 12'h0FC: begin
            mask[dst_idx] = 1'b1; mask[src_idx] = 1'b1;
        end
        12'h021, 12'h023, 12'h025, 12'h0F9, 12'h105, 12'h1E8, 12'h1F0, 12'h086, 12'h027: mask[dst_idx] = 1'b1;
        12'h0FF: begin
            mask[dst_idx] = 1'b1; mask[3'd1] = 1'b1;
        end
        12'h102: begin
            mask[dst_idx] = 1'b1; mask[src_idx] = 1'b1; mask[3'd1] = 1'b1;
        end
        default: ;
    endcase
    recipe_gpr_read_mask = mask;
endfunction

// Entry-point-derived hardwired control generated from the recipe inventory.
function automatic recipe_meta_t recipe_metadata(input dec_entry_t e);
    recipe_meta_t r;
    logic [2:0] grp;
    r = '0;
    if (e.opcode[7:4] == 4'h4 || e.opcode[7:4] == 4'h5)
        r.op_byte = 1'b0;
    else if (e.opcode[7:4] == 4'hB && !e.has_0f)
        r.op_byte = !e.opcode[3];
    else
        r.op_byte = !e.opcode[0];
    grp = ((e.opcode == 8'h80) || (e.opcode == 8'h81) ||
           (e.opcode == 8'h83)) ? e.modrm[5:3] : e.opcode[5:3];
    if (e.rep_lock == PREFIX_NOREPLOCK) begin
        unique case (e.entry_point)
            12'h9C9: begin
                r.hardwired = 1'b1;
            end
            12'h003: begin
                r.hardwired = 1'b1; r.commit_sel = RECIPE_COMMIT_ALU;
                r.reads_src = 1'b1;
            end
            12'h005: begin
                if ((e.opcode[7:4] == 4'hB) ||
                    ((e.opcode[7:1] == 7'b1100011) &&
                     (e.modrm[7:6] == 2'b11) && (e.modrm[5:3] == 3'b000))) begin
                    r.hardwired = 1'b1; r.commit_sel = RECIPE_COMMIT_ALU;
                end
            end
            12'h01D: begin
                r.hardwired = 1'b1; r.commit_sel = RECIPE_COMMIT_ALU;
                r.reads_flags = (grp == 3'b010) || (grp == 3'b011);
                r.reads_dst = 1'b1; r.reads_src = 1'b1;
                r.writes_flags = 1'b1;
            end
            12'h01F: begin
                r.hardwired = 1'b1; r.reads_dst = 1'b1; r.reads_src = 1'b1;
                r.writes_flags = 1'b1;
            end
            12'h021: begin
                r.hardwired = 1'b1; r.commit_sel = RECIPE_COMMIT_ALU;
                r.reads_dst = 1'b1; r.writes_flags = 1'b1;
            end
            12'h023: begin
                if (!e.has_0f && (((e.opcode[7:6] == 2'b00) &&
                    (e.opcode[2:1] == 2'b10)) ||
                    (((e.opcode == 8'h80) || (e.opcode == 8'h81) ||
                      (e.opcode == 8'h83)) && (e.modrm[7:6] == 2'b11) &&
                     (grp != 3'b111)))) begin
                    r.hardwired = 1'b1; r.commit_sel = RECIPE_COMMIT_ALU;
                    r.reads_flags = (grp == 3'b010) || (grp == 3'b011);
                    r.reads_dst = 1'b1; r.writes_flags = 1'b1;
                end
            end
            12'h025: begin
                if (!e.has_0f && (((e.opcode[7:6] == 2'b00) &&
                    (e.opcode[2:1] == 2'b10) && (grp == 3'b111)) ||
                    (((e.opcode == 8'h80) || (e.opcode == 8'h81) ||
                      (e.opcode == 8'h83)) && (e.modrm[7:6] == 2'b11) &&
                     (grp == 3'b111)) || (e.opcode[7:1] == 7'b1010100) ||
                    ((e.opcode[7:1] == 7'b1111011) &&
                     (e.modrm[7:6] == 2'b11) && (e.modrm[5:3] == 3'b000)))) begin
                    r.hardwired = 1'b1; r.reads_dst = 1'b1;
                    r.writes_flags = 1'b1;
                end
            end
            12'h0B9: begin
                if (e.has_modrm && (e.modrm[7:6] != 2'b11)) begin
                    r.hardwired = 1'b1; r.uses_ea = 1'b1;
                    r.writes_srcreg = 1'b1;
                end
            end
            12'h0F9, 12'h105: begin
                if (!e.has_0f && (e.modrm[7:6] == 2'b11) &&
                    (e.modrm[5:3] != 3'b010) && (e.modrm[5:3] != 3'b011) &&
                    (e.modrm[5:3] != 3'b110)) begin
                    r.hardwired = 1'b1; r.multi_ustep = 1'b1;
                    r.commit_sel = RECIPE_COMMIT_SHIFT; r.reads_dst = 1'b1;
                    r.writes_flags = 1'b1;
                end
            end
            12'h0FF: begin
                if (!e.has_0f && (e.modrm[7:6] == 2'b11) &&
                    (e.modrm[5:3] != 3'b010) && (e.modrm[5:3] != 3'b011) &&
                    (e.modrm[5:3] != 3'b110)) begin
                    r.hardwired = 1'b1; r.multi_ustep = 1'b1;
                    r.commit_sel = RECIPE_COMMIT_SHIFT; r.reads_dst = 1'b1;
                    r.reads_ecx = 1'b1; r.writes_flags = 1'b1;
                end
            end
            12'h0FC: begin
                if (e.has_0f && (e.modrm[7:6] == 2'b11) &&
                    ((e.opcode == 8'hA4) || (e.opcode == 8'hAC))) begin
                    r.hardwired = 1'b1; r.multi_ustep = 1'b1;
                    r.commit_sel = RECIPE_COMMIT_SHIFT;
                    r.reads_dst = 1'b1; r.reads_src = 1'b1;
                    r.writes_flags = 1'b1;
                end
            end
            12'h102: begin
                if (e.has_0f && (e.modrm[7:6] == 2'b11) &&
                    ((e.opcode == 8'hA5) || (e.opcode == 8'hAD))) begin
                    r.hardwired = 1'b1; r.multi_ustep = 1'b1;
                    r.commit_sel = RECIPE_COMMIT_SHIFT;
                    r.reads_dst = 1'b1; r.reads_src = 1'b1;
                    r.reads_ecx = 1'b1; r.writes_flags = 1'b1;
                end
            end
            12'h1E8, 12'h1F0: begin
                r.hardwired = 1'b1; r.multi_ustep = 1'b1;
                r.commit_sel = RECIPE_COMMIT_SIGSRC;
                r.writes_srcreg = 1'b1; r.reads_dst = 1'b1;
            end
            12'h013: begin
                r.hardwired = 1'b1; r.slot_has_work = 1'b1; r.uses_ea = 1'b1;
                r.reads_src = 1'b1;
            end
            12'h015: begin
                if ((e.opcode[7:1] == 7'b1100011) &&
                    (e.modrm[7:6] != 2'b11) && (e.modrm[5:3] == 3'b000)) begin
                    r.hardwired = 1'b1; r.slot_has_work = 1'b1; r.uses_ea = 1'b1;
                end
            end
            12'h019: begin
                if (!e.has_0f && (((e.opcode[7:2] == 6'b100010) &&
                    e.opcode[1] && (e.modrm[7:6] != 2'b11)) ||
                    ((e.opcode[7:2] == 6'b101000) && !e.opcode[1]))) begin
                    r.hardwired = 1'b1; r.multi_ustep = 1'b1;
                    r.commit_sel = RECIPE_COMMIT_MEM; r.slot_has_work = 1'b1;
                    r.uses_ea = 1'b1;
                end
            end
            12'h027: begin
                if (!e.has_0f && (e.opcode[7:6] == 2'b00) &&
                    !e.opcode[2] && e.opcode[1] && e.has_modrm &&
                    (e.modrm[7:6] != 2'b11) && (grp != 3'b111)) begin
                    r.hardwired = 1'b1; r.multi_ustep = 1'b1;
                    r.commit_sel = RECIPE_COMMIT_ALU; r.uses_ea = 1'b1;
                    r.reads_flags = (grp == 3'b010) || (grp == 3'b011);
                    r.reads_dst = 1'b1;
                    r.writes_flags = 1'b1;
                end
            end
            12'h02C, 12'h035: begin
                if (!e.has_0f) begin
                    r.hardwired = 1'b1; r.multi_ustep = 1'b1;
                    r.uses_ea = 1'b1; r.writes_flags = 1'b1;
                end
            end
            12'h031: begin
                if (!e.has_0f && (((e.opcode == 8'h80) ||
                    (e.opcode == 8'h81) || (e.opcode == 8'h83)) &&
                    (e.modrm[7:6] != 2'b11) && (grp == 3'b111) ||
                    ((e.opcode[7:1] == 7'b1111011) &&
                     (e.modrm[7:6] != 2'b11) &&
                     (e.modrm[5:3] == 3'b000)))) begin
                    r.hardwired = 1'b1; r.multi_ustep = 1'b1;
                    r.uses_ea = 1'b1; r.writes_flags = 1'b1;
                end
            end
            12'h039: begin
                if (!e.has_0f && ((e.opcode == 8'h80) ||
                    (e.opcode == 8'h81) || (e.opcode == 8'h83)) &&
                    (e.modrm[7:6] != 2'b11) && (grp != 3'b111)) begin
                    r.hardwired = 1'b1; r.multi_ustep = 1'b1;
                    r.slot_has_work = 1'b1; r.uses_ea = 1'b1;
                    r.writes_flags = 1'b1;
                end
            end
            12'h04A: begin
                if (!e.has_0f) begin
                    r.hardwired = 1'b1; r.multi_ustep = 1'b1;
                    r.slot_has_work = 1'b1; r.uses_ea = 1'b1;
                    r.writes_flags = 1'b1;
                end
            end
            12'h1EB, 12'h1F3: begin
                r.hardwired = 1'b1; r.multi_ustep = 1'b1;
                r.commit_sel = RECIPE_COMMIT_SIGSRC;
                r.uses_ea = 1'b1; r.writes_srcreg = 1'b1;
            end
            12'h065: begin
                r.hardwired = 1'b1; r.multi_ustep = 1'b1; r.jcc = 1'b1;
                r.reads_flags = 1'b1; r.br_rel = 1'b1;
            end
            12'h06A: begin
                r.hardwired = 1'b1; r.multi_ustep = 1'b1; r.br_rel = 1'b1;
            end
            12'h075: begin
                r.hardwired = 1'b1; r.multi_ustep = 1'b1;
                if (e.data32) r.commit_sel = RECIPE_COMMIT_ESP;
                r.uses_ea = 1'b1; r.br_rel = 1'b1;
            end
            12'h072: begin
                r.hardwired = 1'b1; r.multi_ustep = 1'b1; r.uses_ea = 1'b1;
            end
            12'h086: begin
                if (e.opcode[7:3] == 5'b01010) begin
                    r.hardwired = 1'b1; r.commit_sel = RECIPE_COMMIT_ESP;
                    r.slot_has_work = 1'b1; r.uses_ea = 1'b1;
                    r.reads_dst = 1'b1;
                end
            end
            12'h09B: begin
                if ((e.opcode[7:6] == 2'b00) && (e.opcode[2:0] == 3'b110)) begin
                    r.hardwired = 1'b1; r.commit_sel = RECIPE_COMMIT_ESP;
                    r.slot_has_work = 1'b1; r.uses_ea = 1'b1;
                end
            end
            12'h09D: begin
                if ((e.opcode == 8'h68) || (e.opcode == 8'h6A)) begin
                    r.hardwired = 1'b1; r.commit_sel = RECIPE_COMMIT_ESP;
                    r.slot_has_work = 1'b1; r.uses_ea = 1'b1;
                end
            end
            12'h09F: begin
                if (e.opcode[7:3] == 5'b01011) begin
                    r.hardwired = 1'b1; r.multi_ustep = 1'b1;
                    r.commit_sel = RECIPE_COMMIT_MEM; r.slot_has_work = 1'b1;
                    r.uses_ea = 1'b1;
                end
            end
            12'h9C5: begin
                // Direct x87 transport; normal sequencer retirement.
                r.commit_sel = RECIPE_ACTION_X87_DIRECT; r.uses_ea = 1'b1;
            end
            12'h9D1: begin
                // Direct x87 transport; normal sequencer retirement.
                r.commit_sel = RECIPE_ACTION_X87_DIRECT; r.uses_ea = 1'b0;
            end
            12'h9D3: begin
                // Direct x87 transport; normal sequencer retirement.
                r.commit_sel = RECIPE_ACTION_X87_DIRECT; r.uses_ea = 1'b1;
            end
            12'h9CB: begin
                // Sequenced BRAM overlay; RD_FAST/WR_FAST own memory only.
                r.uses_ea = 1'b1;
            end
            12'h9CE: begin
                // Sequenced BRAM overlay; RD_FAST/WR_FAST own memory only.
                r.uses_ea = 1'b1;
            end
            default: ;
        endcase
    end
    recipe_metadata = r;
endfunction
