#!/usr/bin/env python3
"""Generate fixed-point lookup tables for FYL2X and F2XM1."""

import math
from pathlib import Path


Q52 = 1 << 52


def emit_function(name: str, width: int, values: list[int]) -> list[str]:
    lines = [
        f"function automatic logic [{width - 1}:0] {name}(",
        "    input logic [9:0] index);",
        "    case (index)",
    ]
    digits = (width + 3) // 4
    lines.extend(
        f"        10'd{index}: return {width}'h{value:0{digits}x};"
        for index, value in enumerate(values)
    )
    lines.extend(("        default: return '0;", "    endcase", "endfunction", ""))
    return lines


def packed_entry(base: int, successor: int) -> int:
    delta = successor - base
    assert 0 <= base < (1 << 54)
    assert -(1 << 45) <= delta < (1 << 45)
    return (base << 46) | (delta & ((1 << 46) - 1))


def packed_entries(log2_values: list[int], exp2_values: list[int],
                   exp2_negative_values: list[int]) -> list[int]:
    entries = []
    for values in (log2_values, exp2_values, exp2_negative_values):
        entries.extend(packed_entry(values[index], values[index + 1])
                       for index in range(256))
    entries.append(packed_entry(exp2_values[256], exp2_values[256]))
    entries.append(packed_entry(exp2_negative_values[256],
                                exp2_negative_values[256]))
    return entries


def emit_mif(entries: list[int]) -> str:
    lines = [
        "WIDTH=100;", f"DEPTH={len(entries)};", "", "ADDRESS_RADIX=HEX;",
        "DATA_RADIX=HEX;", "", "CONTENT BEGIN",
    ]
    for index, entry in enumerate(entries):
        lines.append(f"    {index:03X} : {entry:025X};")
    lines.extend(("END;", ""))
    return "\n".join(lines)


def main() -> None:
    log2_values = [round(math.log2(1.0 + index / 256.0) * Q52)
                   for index in range(257)]
    exp2_values = [round(math.pow(2.0, index / 256.0) * Q52)
                   for index in range(257)]
    exp2_negative_values = [round(math.pow(2.0, -index / 256.0) * Q52)
                            for index in range(257)]

    entries = packed_entries(
        log2_values, exp2_values, exp2_negative_values)

    lines = ["// Generated by build_x87_logexp_tables.py. Do not edit by hand.", ""]
    lines += emit_function("x87_logexp_q52", 100, entries)
    output = Path(__file__).resolve().parent / "x87_logexp_tables.svh"
    output.write_text("\n".join(lines))
    mif_output = Path(__file__).resolve().parent / "x87_logexp_tables.mif"
    mif_output.write_text(emit_mif(entries))


if __name__ == "__main__":
    main()
