#!/usr/bin/env python3
"""Generate length_table.svh: D1's instruction length as two flat tables.

The D1 cursor advance (body length) is on the K1Q -> length -> cursor -> K1Q
loop. Computing it through the control PLA, then has_modrm, then the
immediate-size case, then an add, is a serial chain. This table gives the
opcode-side part, {has_modrm, opcode byte + ModR/M byte + immediate}, straight
from the raw bits, so the loop sees one table lookup in parallel with the
ModR/M displacement decode and a single add.

Like decoder 31's three-byte input (US5293592), the length is a function of
opcode, ModR/M and SIB[2:0]. One table over all of them would have 2^22
entries, so it factors into two that D1 adds:

  opcode side   {has_0f, opcode[7:0], data32, addr32, modrm[5:4] != 0}
                -> {has_modrm, opcode byte + ModR/M byte + immediate}
  ModR/M side   {addr32, modrm[7:6], modrm[2:0], sib[2:0]}
                -> bytes after the ModR/M: SIB byte + displacement

The rules mirror build_struct_work() and capture_sib() in decoder.sv; the
decoder checks the sum against its captured length in simulation on every
handoff.

  gen_length_table.py [--pla pla_control.svh] [--out length_table.svh]
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent


def load_opcode_pla(path: Path) -> list[tuple[str, int]]:
    text = path.read_text()
    body = text.split("function automatic logic [11:0] pla_control_opcode_lookup(")[1]
    body = body.split("endfunction")[0]
    rows = []
    for m in re.finditer(r"9'b([01?])_([01?]{8}):\s*pla_control_opcode_lookup\s*=\s*12'b([01]{12});", body):
        rows.append((m.group(1) + m.group(2), int(m.group(3), 2)))
    if not rows:
        raise SystemExit("no pla_control_opcode_lookup rows found")
    return rows


def pla_lookup(rows, has_0f: int, opcode: int) -> int:
    key = f"{has_0f}{opcode:08b}"
    for pat, val in rows:              # casez: first matching row wins
        if all(p in "?" or p == k for p, k in zip(pat, key)):
            return val
    return 0


def opcode_side(rows, has_0f, opcode, data32, addr32, f67_hi) -> tuple[int, int]:
    ctl = pla_lookup(rows, has_0f, opcode)
    bit = lambda i: (ctl >> i) & 1
    has_modrm = bit(2) & (bit(0) ^ 1)
    if has_modrm:
        s_len = 2
        sel = (ctl >> 10) & 3
        imm = {0: 1, 1: 4 if data32 else 2, 2: 0, 3: 1}[sel]
        if (opcode >> 1) == 0b1111011 and f67_hi:      # F6/F7 /2../7: no immediate
            imm = 0
    else:
        s_len = 1
        if not has_0f and (opcode >> 2) == 0b101000:    # MOV moffs
            imm = 4 if addr32 else 2
        else:
            imm = {
                0b100111: 1,
                0b110111: 4 if data32 else 2,
                0b000111: 1,
                0b010111: 2,
                0b011111: 4 if data32 else 2,
                0b100010: 1,
                0b101111: 3,
                0b111111: 6 if data32 else 4,
            }.get((ctl >> 6) & 0x3F, 0)
    opc_len = s_len + imm
    assert opc_len < 8
    return has_modrm, opc_len


def modrm_side(addr32, mod, rm, sib_base) -> int:
    if mod == 3:
        return 0
    has_sib = addr32 and rm == 0b100
    if mod == 1:
        disp = 1
    elif mod == 2:
        disp = 4 if addr32 else 2
    elif addr32 and has_sib:
        disp = 4 if sib_base == 0b101 else 0
    elif addr32:
        disp = 4 if rm == 0b101 else 0
    else:
        disp = 2 if rm == 0b110 else 0
    return (1 if has_sib else 0) + disp


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--pla", type=Path, default=HERE / "pla_control.svh")
    ap.add_argument("--out", type=Path, default=HERE / "length_table.svh")
    args = ap.parse_args()
    rows = load_opcode_pla(args.pla)

    entries = []
    for idx in range(4096):
        has_0f = (idx >> 11) & 1
        opcode = (idx >> 3) & 0xFF
        data32 = (idx >> 2) & 1
        addr32 = (idx >> 1) & 1
        f67_hi = idx & 1
        has_modrm, opc_len = opcode_side(rows, has_0f, opcode, data32, addr32, f67_hi)
        entries.append((has_modrm << 3) | opc_len)

    lines = [
        "// Generated by scripts/gen_length_table.py from pla_control.svh; do not edit.",
        "// D1 opcode-side length {has_modrm, opcode byte + ModR/M byte + immediate},",
        "// indexed by {has_0f, opcode, data32, addr32, modrm[5:4] != 0}.",
        "localparam logic [4*4096-1:0] D1_LENGTH_TABLE = {",
    ]
    hexes = [f"{e:x}" for e in reversed(entries)]   # entry 0 in the low nibble
    for i in range(0, 4096, 64):
        chunk = "".join(hexes[i:i + 64])
        sep = "," if i + 64 < 4096 else ""
        lines.append(f"    256'h{chunk}{sep}")
    mentries = []
    for idx in range(512):
        addr32 = (idx >> 8) & 1
        mod = (idx >> 6) & 3
        rm = (idx >> 3) & 7
        sib_base = idx & 7
        mentries.append(modrm_side(addr32, mod, rm, sib_base))
    lines += [
        "};",
        "",
        "// D1 ModR/M-side length: SIB byte + displacement after the ModR/M byte,",
        "// indexed by {addr32, modrm[7:6], modrm[2:0], sib[2:0]}.",
        "localparam logic [3*512-1:0] D1_MODRM_LENGTH_TABLE = {",
    ]
    mbits = "".join(f"{e:03b}" for e in reversed(mentries))
    for i in range(0, len(mbits), 192):
        sep = "," if i + 192 < len(mbits) else ""
        lines.append(f"    192'b{mbits[i:i + 192]}{sep}")
    lines += [
        "};",
        "",
        "function automatic logic [3:0] d1_length_lookup(",
        "    input logic       has_0f,",
        "    input logic [7:0] opcode,",
        "    input logic       data32,",
        "    input logic       addr32,",
        "    input logic       modrm_reg_hi",
        ");",
        "    d1_length_lookup = D1_LENGTH_TABLE[{has_0f, opcode, data32, addr32, modrm_reg_hi} * 4 +: 4];",
        "endfunction",
        "",
        "function automatic logic [2:0] d1_modrm_length_lookup(",
        "    input logic       addr32,",
        "    input logic [7:0] modrm,",
        "    input logic [2:0] sib_base",
        ");",
        "    d1_modrm_length_lookup =",
        "        D1_MODRM_LENGTH_TABLE[{addr32, modrm[7:6], modrm[2:0], sib_base} * 3 +: 3];",
        "endfunction",
        "",
    ]
    args.out.write_text("\n".join(lines))
    print(f"wrote {args.out} ({len(entries)} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
